# Use an official Python runtime as a parent image
FROM python:3.12-slim

ARG POSTGRESQL_DATABASE_URL
ARG REDIS_DATABASE_URL
ARG CACHE_TTL_SECONDS
ARG BACKEND_API_URL
ARG USE_MOCK_BACKEND_API_URL
ARG MOCK_BACKEND_API_URL
ARG OPENAI_API_KEY
ARG LLM_PROVIDER
ARG LLM_MODEL
ARG LLM_MAX_TOKENS
ARG LLM_TEMPERATURE
ARG LLM_TIMEOUT_SECONDS
ARG LLM_RETRY_ATTEMPTS
ARG EMBEDDING_MODEL
ARG EMBEDDING_SIMILARITY_THRESHOLD
ARG ENABLE_LLM_MATCHING
ARG ENABLE_SEMANTIC_MATCHING

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV POSTGRESQL_DATABASE_URL=$POSTGRESQL_DATABASE_URL
ENV REDIS_DATABASE_URL=$REDIS_DATABASE_URL
ENV CACHE_TTL_SECONDS=$CACHE_TTL_SECONDS
ENV BACKEND_API_URL=$BACKEND_API_URL
ENV USE_MOCK_BACKEND_API_URL=$USE_MOCK_BACKEND_API_URL
ENV MOCK_BACKEND_API_URL=$MOCK_BACKEND_API_URL
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV LLM_PROVIDER=$LLM_PROVIDER
ENV LLM_MODEL=$LLM_MODEL
ENV LLM_MAX_TOKENS=$LLM_MAX_TOKENS
ENV LLM_TEMPERATURE=$LLM_TEMPERATURE
ENV LLM_TIMEOUT_SECONDS=$LLM_TIMEOUT_SECONDS
ENV LLM_RETRY_ATTEMPTS=$LLM_RETRY_ATTEMPTS
ENV EMBEDDING_MODEL=$EMBEDDING_MODEL
ENV EMBEDDING_SIMILARITY_THRESHOLD=$EMBEDDING_SIMILARITY_THRESHOLD
ENV ENABLE_LLM_MATCHING=$ENABLE_LLM_MATCHING
ENV ENABLE_SEMANTIC_MATCHING=$ENABLE_SEMANTIC_MATCHING

# Set the working directory in the container to /home
WORKDIR /home

# Create apa directory inside /home
RUN mkdir /home/app

# Add the module directory contents into the container at /home/app
ADD ./app /home/app

RUN ls -R /home

# Copy the requirements file into the container at /home
ADD ./requirements.txt /home

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run app.py when the container launches
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
